export interface SiteData {
  id: string;
  title: string;
  titleNe: string;
  location: string;
  locationNe: string;
  distance: string;
  description: string;
  descriptionNe: string;
  image: any;
  category: string;
  latitude: number;
  longitude: number;
}

const IMAGES = [
  require('../assets/images/timeline_1.png'),
  require('../assets/images/timeline_2.png'),
  require('../assets/images/timeline_3.png'),
  require('../assets/images/timeline_4.png'),
  require('../assets/images/timeline_5.png'),
  require('../assets/images/temple_hero.png'),
  require('../assets/images/Maya Devi Temple.jpg'),
];

export const SITES: Record<string, SiteData> = {
  // Sacred Garden Core
  maya_devi: {
    id: 'maya_devi',
    title: 'Maya Devi Temple',
    titleNe: 'माया देवी मन्दिर',
    location: 'Sacred Garden',
    locationNe: 'पवित्र बगैचा',
    distance: '150m away',
    description: 'The spiritual heart of Lumbini, marking the exact spot of the Buddha\'s birth.',
    descriptionNe: 'लुम्बिनीको आध्यात्मिक मुटु, जहाँ बुद्धको जन्म भएको ठ्याक्कै स्थान चिन्हित छ।',
    image: IMAGES[6],
    category: 'SACRED SITE',
    latitude: 27.4696334,
    longitude: 83.2758452
  },
  pillar_ashoka: {
    id: 'pillar_ashoka',
    title: 'Ashoka Pillar',
    titleNe: 'अशोक स्तम्भ',
    location: 'Sacred Garden',
    locationNe: 'पवित्र बगैचा',
    distance: '100m away',
    description: 'Erected by Emperor Ashoka in 249 BC, providing the oldest monumental evidence of Buddha’s birthplace.',
    descriptionNe: 'सम्राट अशोक द्वारा २४९ ईसा पूर्वमा खडा गरिएको, बुद्धको जन्मस्थानको सबैभन्दा पुरानो प्रमाण।',
    image: IMAGES[1],
    category: 'SACRED SITE',
    latitude: 27.4696,
    longitude: 83.2757
  },
  puskarini_pond: {
    id: 'puskarini_pond',
    title: 'Puskarini Pond',
    titleNe: 'पुष्करिणी पोखरी',
    location: 'Sacred Garden',
    locationNe: 'पवित्र बगैचा',
    distance: '120m away',
    description: 'The holy pond where Queen Maya Devi is believed to have bathed before giving birth.',
    descriptionNe: 'पवित्र पोखरी जहाँ रानी माया देवीले बुद्धलाई जन्म दिनु अघि स्नान गरेको विश्वास गरिन्छ।',
    image: IMAGES[2],
    category: 'SACRED SITE',
    latitude: 27.4697,
    longitude: 83.2760
  },
  museum: {
    id: 'museum',
    title: 'Lumbini Museum',
    titleNe: 'लुम्बिनी संग्रहालय',
    location: 'Cultural Zone',
    locationNe: 'सांस्कृतिक क्षेत्र',
    distance: '800m away',
    description: 'A rich collection of artifacts illustrating the life and teachings of Buddha.',
    descriptionNe: 'बुद्धको जीवन र शिक्षाहरू चित्रण गर्ने कलाकृतिहरूको समृद्ध संग्रह।',
    image: IMAGES[3],
    category: 'CULTURAL SITE',
    latitude: 27.4891667,
    longitude: 83.2772222
  },
  pagoda_peace: {
    id: 'pagoda_peace',
    title: 'World Peace Pagoda',
    titleNe: 'विश्व शान्ति स्तूप',
    location: 'Shanti Deep',
    locationNe: 'शान्ति दीप',
    distance: '2km away',
    description: 'A massive white stupa built by Japanese Buddhists symbolizing global harmony.',
    descriptionNe: 'जापानी बौद्धहरूद्वारा निर्मित एक विशाल सेतो स्तूप, जसले विश्वव्यापी सद्भावको प्रतीक गर्दछ।',
    image: IMAGES[4],
    category: 'STUPA',
    latitude: 27.4955,
    longitude: 83.2748
  },
  peace_flame: {
    id: 'peace_flame',
    title: 'World Peace Flame',
    titleNe: 'शान्ति दीप',
    location: 'Central canal',
    locationNe: 'केन्द्रीय नहर',
    distance: '500m away',
    description: 'An eternal flame brought from the UN, symbolizing global peace.',
    descriptionNe: 'संयुक्त राष्ट्र संघबाट ल्याइएको एक अनन्त ज्वाला, जसले विश्वव्यापी शान्तिको प्रतीक गर्दछ।',
    image: IMAGES[5],
    category: 'MONUMENT',
    latitude: 27.4855,
    longitude: 83.2765
  },

  // East Monastic Zone (Theravada)
  monastery_thai: {
    id: 'monastery_thai',
    title: 'Royal Thai Monastery',
    titleNe: 'शाही थाई मन्दिर',
    location: 'East Monastic Zone',
    locationNe: 'पूर्वी विहार क्षेत्र',
    distance: '1.5km away',
    description: 'Elegant white marble temple built in traditional Thai architecture style.',
    descriptionNe: 'परम्परागत थाई वास्तुकला शैलीमा निर्मित सुरुचिपूर्ण सेतो संगमरमरको मन्दिर।',
    image: IMAGES[0],
    category: 'THAILAND',
    latitude: 27.4870,
    longitude: 83.2798
  },
  monastery_myanmar: {
    id: 'monastery_myanmar',
    title: 'Myanmar Golden Temple',
    titleNe: 'बर्मेली सुनौलो मन्दिर',
    location: 'East Monastic Zone',
    locationNe: 'पूर्वी विहार क्षेत्र',
    distance: '1.2km away',
    description: 'A beautiful golden pagoda built in traditional Burmese style.',
    descriptionNe: 'परम्परागत बर्मेली शैलीमा निर्मित एक सुन्दर सुनौलो प्यागोडा।',
    image: IMAGES[1],
    category: 'MYANMAR',
    latitude: 27.4862,
    longitude: 83.2721
  },
  monastery_cambodia: {
    id: 'monastery_cambodia',
    title: 'Cambodian Monastery',
    titleNe: 'कम्बोडियन मन्दिर',
    location: 'East Monastic Zone',
    locationNe: 'पूर्वी विहार क्षेत्र',
    distance: '1.4km away',
    description: 'Features intricate Angkor Wat-inspired carvings and architecture.',
    descriptionNe: 'अंकोर वाटबाट प्रेरित जटिल नक्काशी र वास्तुकला।',
    image: IMAGES[2],
    category: 'CAMBODIA',
    latitude: 27.4865,
    longitude: 83.2785
  },
  monastery_lanka: {
    id: 'monastery_lanka',
    title: 'Sri Lankan Monastery',
    titleNe: 'श्रीलंकन मन्दिर',
    location: 'East Monastic Zone',
    locationNe: 'पूर्वी विहार क्षेत्र',
    distance: '1.3km away',
    description: 'Sri Lanka Maha Vihara, featuring a prominent white dome architecture.',
    descriptionNe: 'श्रीलंका महाविहार, एक प्रमुख सेतो गुम्बज वास्तुकला भएको।',
    image: IMAGES[3],
    category: 'SRI LANKA',
    latitude: 27.4860,
    longitude: 83.2790
  },
  monastery_india: {
    id: 'monastery_india',
    title: 'Mahabodhi Society',
    titleNe: 'महाबोधि समाज',
    location: 'East Monastic Zone',
    locationNe: 'पूर्वी विहार क्षेत्र',
    distance: '1.1km away',
    description: 'Representative of Indian Buddhist communities and Mahabodhi Society.',
    descriptionNe: 'भारतीय बौद्ध समुदाय र महाबोधि समाजको प्रतिनिधि।',
    image: IMAGES[4],
    category: 'INDIA',
    latitude: 27.4858,
    longitude: 83.2795
  },
  monastery_canada: {
    id: 'monastery_canada',
    title: 'Canadian Monastery',
    titleNe: 'क्यानेडियन मन्दिर',
    location: 'East Monastic Zone',
    locationNe: 'पूर्वी विहार क्षेत्र',
    distance: '1.6km away',
    description: 'Modern representative site of the Canadian Engaged Buddhism Association.',
    descriptionNe: 'क्यानडा इन्गेज्ड बुद्धिज्म एसोसिएसनको आधुनिक प्रतिनिधि स्थल।',
    image: IMAGES[5],
    category: 'CANADA',
    latitude: 27.4850,
    longitude: 83.2778
  },
  monastery_singapore: {
    id: 'monastery_singapore',
    title: 'Singapore Monastery',
    titleNe: 'सिंगापुर मन्दिर',
    location: 'East Monastic Zone',
    locationNe: 'पूर्वी विहार क्षेत्र',
    distance: '1.7km away',
    description: 'A peaceful representative site of Singaporean Buddhist tradition.',
    descriptionNe: 'सिंगापुरको बौद्ध परम्पराको एक शान्त प्रतिनिधि स्थल।',
    image: IMAGES[0],
    category: 'SINGAPORE',
    latitude: 27.4845,
    longitude: 83.2775
  },

  // West Monastic Zone (Mahayana/Vajrayana)
  monastery_chinese: {
    id: 'monastery_chinese',
    title: 'Zhong Hua Chinese',
    titleNe: 'चिनियाँ मन्दिर',
    location: 'West Monastic Zone',
    locationNe: 'पश्चिम विहार क्षेत्र',
    distance: '1.4km away',
    description: 'A grand complex that resembles Beijing\'s Forbidden City.',
    descriptionNe: 'बेइजिङको प्रतिबन्धित सहरजस्तै देखिने एक भव्य परिसर।',
    image: IMAGES[1],
    category: 'CHINA',
    latitude: 27.4875,
    longitude: 83.2715
  },
  monastery_german: {
    id: 'monastery_german',
    title: 'Great Lotus Stupa',
    titleNe: 'जर्मन स्तूप',
    location: 'West Monastic Zone',
    locationNe: 'पश्चिम विहार क्षेत्र',
    distance: '1.6km away',
    description: 'A magnificent German stupa known for its hollow glass crown.',
    descriptionNe: 'यसको खाली गिलास मुकुटको लागि चिनिने एक भव्य जर्मन स्तूप।',
    image: IMAGES[2],
    category: 'GERMANY',
    latitude: 27.4880,
    longitude: 83.2720
  },
  monastery_korean: {
    id: 'monastery_korean',
    title: 'Dae Sung Shakya',
    titleNe: 'कोरियन मन्दिर',
    location: 'West Monastic Zone',
    locationNe: 'पश्चिम विहार क्षेत्र',
    distance: '2.2km away',
    description: 'Korean monastery noted for its colourful ceiling murals and grand hall.',
    descriptionNe: 'यसको रंगीन छत भित्तिचित्र र भव्य हलको लागि चिनिने कोरियाली मन्दिर।',
    image: IMAGES[3],
    category: 'SOUTH KOREA',
    latitude: 27.4925,
    longitude: 83.2750
  },
  monastery_japan: {
    id: 'monastery_japan',
    title: 'Japanese Monastery',
    titleNe: 'जापानी मन्दिर',
    location: 'West Monastic Zone',
    locationNe: 'पश्चिम विहार क्षेत्र',
    distance: '1.8km away',
    description: 'Sokyo temple built in traditional wooden Japanese architectural style.',
    descriptionNe: 'परम्परागत काठको जापानी वास्तुकला शैलीमा निर्मित सोक्यो मन्दिर।',
    image: IMAGES[4],
    category: 'JAPAN',
    latitude: 27.4900,
    longitude: 83.2730
  },
  monastery_vietnam: {
    id: 'monastery_vietnam',
    title: 'Vietnam Phat Quoc Tu',
    titleNe: 'भियतनाम मन्दिर',
    location: 'West Monastic Zone',
    locationNe: 'पश्चिम विहार क्षेत्र',
    distance: '1.9km away',
    description: 'Features a grand roof and unique artificial mountains in its landscape.',
    descriptionNe: 'यसको वास्तुकलामा भव्य छत र अद्वितीय कृत्रिम पहाडहरू छन्।',
    image: IMAGES[5],
    category: 'VIETNAM',
    latitude: 27.4895,
    longitude: 83.2710
  },
  world_center_peace: {
    id: 'world_center_peace',
    title: 'World Center for Peace and Unity',
    titleNe: 'विश्व शान्ति र एकता केन्द्र',
    location: 'East Monastic Zone',
    locationNe: 'पूर्वी विहार क्षेत्र',
    distance: '1.3km away',
    description: 'The monumental Buddhist Library and Research Center.',
    descriptionNe: 'स्मारक बौद्ध पुस्तकालय र अनुसन्धान केन्द्र।',
    image: IMAGES[1],
    category: 'CULTURAL',
    latitude: 27.4855,
    longitude: 83.2775
  },
  monastery_austria: {
    id: 'monastery_austria',
    title: 'Austrian Temple',
    titleNe: 'अस्ट्रियन मन्दिर',
    location: 'West Monastic Zone',
    locationNe: 'पश्चिम विहार क्षेत्र',
    distance: '2.1km away',
    description: 'Also known as the Temple of the Graduated Path.',
    descriptionNe: 'ग्रेजुएटेड पाथको मन्दिरको रूपमा पनि चिनिन्छ।',
    image: IMAGES[1],
    category: 'AUSTRIA',
    latitude: 27.4885,
    longitude: 83.2700
  },
  monastery_nepal: {
    id: 'monastery_nepal',
    title: 'Manang Samaj Stupa',
    titleNe: 'मनाङ समाज स्तूप',
    location: 'West Monastic Zone',
    locationNe: 'पश्चिम विहार क्षेत्र',
    distance: '2.3km away',
    description: 'Nepalese stupa decorated with traditional local murals and arts.',
    descriptionNe: 'परम्परागत स्थानीय भित्तिचित्र र कलाले सजिएको नेपाली स्तूप।',
    image: IMAGES[2],
    category: 'NEPAL',
    latitude: 27.4915,
    longitude: 83.2740
  },
  monastery_urgen: {
    id: 'monastery_urgen',
    title: 'Urgen Dorjee Centre',
    titleNe: 'उर्गेन दोर्जी केन्द्र',
    location: 'West Monastic Zone',
    locationNe: 'पश्चिम विहार क्षेत्र',
    distance: '2.4km away',
    description: 'Represents the Tibetan Vajrayana tradition in Lumbini.',
    descriptionNe: 'लुम्बिनीमा तिब्बती वज्रयान परम्पराको प्रतिनिधित्व गर्दछ।',
    image: IMAGES[3],
    category: 'TIBETAN',
    latitude: 27.4910,
    longitude: 83.2735
  },
  monastery_russia: {
    id: 'monastery_russia',
    title: 'Russian Monastery',
    titleNe: 'रुसी मन्दिर',
    location: 'West Monastic Zone',
    locationNe: 'पश्चिम विहार क्षेत्र',
    distance: '2.5km away',
    description: 'Representative of Russian Buddhist practitioners, established in 2023.',
    descriptionNe: 'रुसी बौद्ध चिकित्सकहरूको प्रतिनिधि, २०२३ मा स्थापित।',
    image: IMAGES[4],
    category: 'RUSSIA',
    latitude: 27.4905,
    longitude: 83.2745
  },
  monastery_bangladesh: {
    id: 'monastery_bangladesh',
    title: 'Bangladesh Monastery',
    titleNe: 'बंगलादेश मन्दिर',
    location: 'West Monastic Zone',
    locationNe: 'पश्चिम विहार क्षेत्र',
    distance: '2.6km away',
    description: 'Planned representative monastery of the Bangladeshi Buddhist community.',
    descriptionNe: 'बंगलादेशी बौद्ध समुदायको नियोजित प्रतिनिधि मन्दिर।',
    image: IMAGES[5],
    category: 'BANGLADESH',
    latitude: 27.4920,
    longitude: 83.2760
  },
  monastery_kudan: {
    id: 'monastery_kudan',
    title: 'Kudan Stupa',
    titleNe: 'कुदान स्तूप',
    location: 'Historical Zone',
    locationNe: 'ऐतिहासिक क्षेत्र',
    distance: '3.0km away',
    description: 'Nearby historical site where Buddha met his father after enlightenment.',
    descriptionNe: 'नजिकैको ऐतिहासिक स्थल जहाँ बुद्धले बुद्धत्व प्राप्ति पछि आफ्नो बुबालाई भेटेका थिए।',
    image: IMAGES[0],
    category: 'HISTORY',
    latitude: 27.4940,
    longitude: 83.2700
  },
  stupa_lotus: {
    id: 'stupa_lotus',
    title: 'Lotus Stupa',
    titleNe: 'कमल स्तूप',
    location: 'West Monastic Zone',
    locationNe: 'पश्चिम विहार क्षेत्र',
    distance: '1.7km away',
    description: 'A beautiful lotus-shaped stupa representing purity and peace.',
    descriptionNe: 'पवित्रता र शान्तिको प्रतिनिधित्व गर्ने एक सुन्दर कमल आकारको स्तूप।',
    image: IMAGES[1],
    category: 'STUPA',
    latitude: 27.4872,
    longitude: 83.2725
  },
  center_meditation: {
    id: 'center_meditation',
    title: 'Panditarama Center',
    titleNe: 'पण्डिताराम ध्यान केन्द्र',
    location: 'Monastic Zone',
    locationNe: 'विहार क्षेत्र',
    distance: '1.9km away',
    description: 'A serene Vipassana meditation center for global practitioners.',
    descriptionNe: 'विश्वव्यापी चिकित्सकहरूको लागि एक शान्त विपश्यना ध्यान केन्द्र।',
    image: IMAGES[2],
    category: 'MEDITATION',
    latitude: 27.4882,
    longitude: 83.2770
  },
  vihara_dharma: {
    id: 'vihara_dharma',
    title: 'Dharma Swami Vihara',
    titleNe: 'धर्म स्वामी विहार',
    location: 'West Monastic Zone',
    locationNe: 'पश्चिम विहार क्षेत्र',
    distance: '2.1km away',
    description: 'Sakya tradition monastery with intricate architecture.',
    descriptionNe: 'जटिल वास्तुकला भएको शाक्य परम्पराको विहार।',
    image: IMAGES[3],
    category: 'SAKYA',
    latitude: 27.4892,
    longitude: 83.2712
  },
  pagoda_golden: {
    id: 'pagoda_golden',
    title: 'Golden Pagoda',
    titleNe: 'स्वर्ण मन्दिर',
    location: 'East Monastic Zone',
    locationNe: 'पूर्वी विहार क्षेत्र',
    distance: '1.2km away',
    description: 'Glistening golden pagoda reflecting Burmese spiritual heritage.',
    descriptionNe: 'बर्मेली आध्यात्मिक विरासत झल्काउने चम्किलो स्वर्ण मन्दिर।',
    image: IMAGES[4],
    category: 'MONUMENT',
    latitude: 27.4862,
    longitude: 83.2732
  },
  monastery_thai_old: {
    id: 'monastery_thai_old',
    title: 'Old Thai Temple',
    titleNe: 'पुरानो थाई मन्दिर',
    location: 'East Monastic Zone',
    locationNe: 'पूर्वी विहार क्षेत्र',
    distance: '1.5km away',
    description: 'Historical Thai representative site in the early development zone.',
    descriptionNe: 'प्रारम्भिक विकास क्षेत्रमा ऐतिहासिक थाई प्रतिनिधि स्थल।',
    image: IMAGES[5],
    category: 'HISTORY',
    latitude: 27.4878,
    longitude: 83.2788
  },
  utility_buspark: {
    id: 'utility_buspark',
    title: 'Lumbini Buspark',
    titleNe: 'लुम्बिनी बसपार्क',
    location: 'Northern Entrance',
    locationNe: 'उत्तरी प्रवेशद्वार',
    distance: 'North end of canal',
    description: 'The main transportation hub for local and long-distance buses to Lumbini.',
    descriptionNe: 'लुम्बिनीका लागि स्थानीय र लामो दूरीका बसहरूको मुख्य यातायात केन्द्र।',
    image: IMAGES[0],
    category: 'TRANSPORT',
    latitude: 27.4903848,
    longitude: 83.2748545
  },
  office_ldt: {
    id: 'office_ldt',
    title: 'LDT Office',
    titleNe: 'लुम्बिनी विकास कोष कार्यालय',
    location: 'Near Sacred Garden',
    locationNe: 'पवित्र बगैचा नजिकै',
    distance: '200m from Temple',
    description: 'The administrative headquarters of the Lumbini Development Trust.',
    descriptionNe: 'लुम्बिनी विकास कोषको प्रशासनिक प्रधान कार्यालय।',
    image: IMAGES[3],
    category: 'OFFICE',
    latitude: 27.4692401,
    longitude: 83.2784458
  },
  monastery_nava_maitri: {
    id: 'monastery_nava_maitri',
    title: 'Nava Maitri Maha Viharaya',
    titleNe: 'नव मैत्री महा विहार',
    location: 'Near Sacred Garden',
    locationNe: 'पवित्र बगैचा नजिकै',
    distance: '150m from Temple',
    description: 'A serene monastery located near the Maya Devi Temple, representing traditional Buddhist architecture and worship.',
    descriptionNe: 'माया देवी मन्दिर नजिकै अवस्थित एक शान्त विहार, जसले परम्परागत बौद्ध वास्तुकला र उपासनाको प्रतिनिधित्व गर्दछ।',
    image: IMAGES[4],
    category: 'MONASTERY',
    latitude: 27.4691262,
    longitude: 83.2769067
  },
  utility_helipad: {
    id: 'utility_helipad',
    title: 'Helicopter Pad',
    titleNe: 'हेलिप्याड',
    location: 'Near Museum',
    locationNe: 'संग्रहालय नजिकै',
    distance: '300m from Museum',
    description: 'The official helicopter landing pad for Lumbini, used for VVIP arrivals and emergency services.',
    descriptionNe: 'लुम्बिनीको लागि आधिकारिक हेलिकप्टर अवतरण प्याड।',
    image: IMAGES[5],
    category: 'TRANSPORT',
    latitude: 27.4902469,
    longitude: 83.2773881
  },
  utility_helipad_2: {
    id: 'utility_helipad_2',
    title: 'Heli Pad (North)',
    titleNe: 'उत्तर हेलिप्याड',
    location: 'Near Museum',
    locationNe: 'संग्रहालय नजिकै',
    distance: '350m from Museum',
    description: 'The secondary helicopter landing pad (lumbini heli pad) located at the northern entrance area.',
    descriptionNe: 'उत्तरी प्रवेश क्षेत्रमा अवस्थित दोस्रो हेलिकप्टर अवतरण प्याड।',
    image: IMAGES[0],
    category: 'TRANSPORT',
    latitude: 27.4907759,
    longitude: 83.2771325
  },
  institute_research: {
    id: 'institute_research',
    title: 'Research Institute',
    titleNe: 'अनुसन्धान संस्थान',
    location: 'Near Museum',
    locationNe: 'संग्रहालय नजिकै',
    distance: '100m from Museum',
    description: 'A dedicated center for Buddhist studies, research, and documentation.',
    descriptionNe: 'बौद्ध अध्ययन, अनुसन्धान र दस्तावेजीकरणका लागि समर्पित केन्द्र।',
    image: IMAGES[1],
    category: 'CULTURAL SITE',
    latitude: 27.4892425,
    longitude: 83.2785294
  },
  center_meditation_intl: {
    id: 'center_meditation_intl',
    title: 'Meditation Center',
    titleNe: 'ध्यान केन्द्र',
    location: 'Near Museum',
    locationNe: 'संग्रहालय नजिकै',
    distance: '200m from Museum',
    description: 'Lumbini International Buddhist Meditation Center - A premier facility for international practitioners.',
    descriptionNe: 'लुम्बिनी अन्तर्राष्ट्रिय बौद्ध ध्यान केन्द्र - अन्तर्राष्ट्रिय चिकित्सकहरूका लागि एक प्रमुख सुविधा।',
    image: IMAGES[2],
    category: 'MEDITATION',
    latitude: 27.4903406,
    longitude: 83.2803034
  }
};
